### ISSUE TITLE
Unknown dimmer

### ISSUE THREAD

**Issue by zeuslooye** [robb-smarrt/nl.ROBBshop.ROBB-smarrt#4]
Hè 
I have bought some dimmers from Robb smarrt. I cant get them to work in homey.
After contact with athom it looks like my dimmers are not recognized as a Robb Smarrt device. 
Can you fix this

Gr 
Jeroen

**Comment by jalbrink** [comment]
Got the same. Looks like manufacture and device Id do not match the driver. It's the zigbee 3 wire dimmer. Driver expects 'sunricher' and some device Id code while the dimmer it self sends "ROBBSmarrt" and they're own device id code

**Comment by TedTolboom** [comment]
Hi @zeuslooye and @jalbrink,

Thanks for reporting; the new dimmer firmware arrived a bit earlier than expected. 
Should be fixed in v1.1.2 which is awaiting app store approval (will bump Athom to approve as soon as possible).

I will close this issue, please re-open if not fixed.

**Comment by TedTolboom** [comment]
v1.1.2 is available in the app store

**Comment by jalbrink** [comment]
Update geïnstalleerd maar het werkt nog niet. Is de manufacture en device
is case sensitive? Het is namelijk "ROBB Smarrt" en niet "ROBB smarrt".
Bijlages toegevoegd.


Mvg,

Jannes

**Comment by TedTolboom** [comment]
Hi @jalbrink,

Thanks for reporting back; should now be fixed in v1.1.3.
Appologies for the delay.

Kind regards,

Ted

**Comment by jalbrink** [comment]
When will it be released?

**Comment by TedTolboom** [comment]
I just received the approval from Athom for this app update and published it to the App Store; should be available within 15 minutes

If you could confirm that it is now working correctly; I would appreciate it. Otherwise I’ll need to find a way to debug it remotely (from our holiday address).

**Comment by jalbrink** [comment]
Is added to the app now, thanks alot :)

**Comment by TedTolboom** [comment]
Thanks for the confirmation and enjoy the device!
