### ISSUE TITLE
Add support for more Sunricher devices?

### ISSUE THREAD

**Issue by mpunktnuSupport** [robb-smarrt/nl.ROBBshop.ROBB-smarrt#5]
What would you need to add support for more devices from Sunricher, for example https://www.sunricher.com/50w-constant-current-zigbee-led-dimmable-driver-srp-zg9105-50w-cc.html ?

Please see attached image for some more info on this device when included as a general Zigbee device on Homey.

![IMG_20190926_114650](https://user-images.githubusercontent.com/48584350/65678556-d0b5e600-e053-11e9-9939-90cd4f2c29c7.jpg)

**Comment by TedTolboom** [comment]
Hi @mpunktnuSupport, support for the LED-dimmer / driver devices is planned to be added in release 1.3. The second release from now.

**Comment by mpunktnuSupport** [comment]
> Hi @mpunktnuSupport, support for the LED-dimmer / driver devices is planned to be added in release 1.3. The second release from now.

That is awesome! Thank you for letting us know.
