### ISSUE TITLE
4 chan robsmart zwave remote & Homey

### ISSUE THREAD

**Issue by lboshuizen** [robb-smarrt/nl.ROBBshop.ROBB-smarrt#7]
## symptoom:
Inclusion van remote in Homey resulteerd in [Simple ZWave device].

## oorzaak
Mogelijke oorzaak mismatch tussen door device verzonden productId en verwachte productId door device/driver in RobbSmartt app.

Device rapporteerd `[productId: 45826]` driver verwacht: `[productId: 41730]`

Note:
45826 = 0xB302
41730 = 0xA302

### homey zwave log

_Na filteren en verwijderen van noise uit de homey-zwave-log:_

Response van device op `[INTERVIEW_MANUFACTURER_SPECIFIC]`

```
Node[29]: [COMMAND_CLASS_MANUFACTURER_SPECIFIC] 
{
  "Manufacturer ID": { "value":816 },
  "Product Type ID": { "value":768 },
  "Product ID":      { "value":45826 }
}
```

### definitie in driver-src  

[`github.com/robb-smarrt/nl.ROBBshop.ROBB-smarrt/drivers/ZW_Remote_4/driver.compose.json [master] line 35:`](https://github.com/robb-smarrt/nl.ROBBshop.ROBB-smarrt/blob/master/drivers/ZW_Remote_4/driver.compose.json)

```javascript
...
"zwave": {
		"manufacturerId": 816,
		"productTypeId": 768,
		"productId": 41730,
               ...
}
...
```

**Comment by TedTolboom** [comment]
Hi @lboshuizen,

Thanks for reporting. 
I just verified and reproduced this issue; for both the 4- and 5-channel remotes.

I'll add the additional productID's to the app in the next release; available in the next day(s). Ok?

**Comment by lboshuizen** [comment]
Thank you.

**Comment by lboshuizen** [comment]
I don't see a commit, I don't see a merge, I don't see a new version in the App Store.

Seems that we have a different view on release management.

**Comment by TedTolboom** [comment]
@lboshuizen appologies for the late fix.

version 1.3.2, which will fix this issue (verified), is submitted for approval in the app store, but can already be installed through the following link: https://homey.app/a/nl.ROBBshop.ROBB-smarrt/test/

I will close this issue. If the issue remains, please re-open this issue.
